### ISSUE TITLE
Error while using service accounts

### ISSUE THREAD

**Issue by rocketgithub** [mvsjes2/p5-google-restapi#11]
While using service accounts, there is an error because the lib is using the wrong subroutine name:

Undefined subroutine &Google::RestApi::Auth::ServiceAccount::config_file called at /Google/RestApi/Auth/ServiceAccount.pm line 19.

Pull request #10 fixes this

**Comment by mvsjes2** [comment]
Thanks for the PR. I'll look into creating some tests for this. I've not used service accounts myself.

**Comment by rocketgithub** [comment]
Thanks for the library, it's been very useful
