### ISSUE TITLE
`${^TYPE_PARAMS_MULTISIG}` is deprecated

### ISSUE THREAD

**Issue by tobyink** [mvsjes2/p5-google-restapi#12]
https://github.com/mvsjes2/p5-google-restapi/blob/e66251c2b4f2b0c04ab21b39dd244fc58aef9c39/lib/Google/RestApi/SheetsApi4/Range.pm#L143

`${^_TYPE_PARAMS_MULTISIG}` (with an extra underscore) is its replacement in Type::Params v2.

`${^TYPE_PARAMS_MULTISIG}` is still supported, but support will be removed in about six months.

This is because the next version of the Perl may introduce new warnings or errors related to these variables. See https://github.com/Perl/RFCs/pull/22.

**Comment by mvsjes2** [comment]
Updated for now to support both, to allow older Type::Params to continue to be used. Will remove the old variable name when the warnings start.
